### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by tomquirk**
Wow... what a slog 😂 

This pull request is a result of the Refactor project (detailed in the [Github Project](https://github.com/mjkaufer/Messer/projects/1)). I've been chipping away at this over the last couple of months and now I think it's ready to go. Tl;dr - most of the open Issues are resolved.

I won't list all the tickets fixed - see the [project]((https://github.com/mjkaufer/Messer/projects/1)) for that.

I understand that this is a pretty significant change in the codebase (nay, almost total rewrite) and am open to suggestions to make it more readable/extensible etc. I've really tried to keep in mind extensibility. There are a bunch of features in the API that could be utilized, and, in my head at least, it should be easy for people to dupe out existing commands/event handlers to make their own which will ultimately help the growth of the project.

I'll wait for you thoughts @mjkaufer 🎉

### CODE REVIEW

**Comment by mjkaufer** [comment]
Hey @tomquirk, thanks for tackling this! My week is ridiculously busy right now, but I should have a lot more time come Monday. I'll try to look at it then - pester me if I don't get around to it by the 22nd

**Comment by tomquirk** [comment]
ping @mjkaufer 😺

**Comment by mjkaufer** [comment]
@tomquirk sorry for the delay, just glanced over it and it looks beautiful! Thanks so much for doing this. The last thing I ask of you is to bump the version from whatever it is now to `0.2.0`! Thanks again for trudging through the ugly mess that was this code base, and making it beautiful!

**Comment by tomquirk** [comment]
@mjkaufer v0.2.0!!!!!!!!

S H I P  I T :partyparrot:

**Comment by mjkaufer** [comment]
@tomquirk Just pushed to npm, version 0.2 is live!

**Pull request merged**
